apiVersion: v1
kind: Secret
metadata: 
  namespace: three-tier-app
  name: mongo-sec
type: Opaque
data:  
  password: QWRtaW5AMTIzCg==   #Admin@123   [echo 'Admin@123' | base64]
  username: QWRtaW4K #admin
